version: '3.1'

services:
  wordpress:
    depends_on:
     - mysql
    image: 'wordpress:latest'
    restart: always
    ports:
        - 8080:80
    environment:
        WORDPRESS_DB_HOST: db:3306
        WORDPRESS_DB_USER: exampleuser
        WORDPRESS_DB_PASSWORD: examplepass
        WORDPRESS_DB_NAME: wordpress
    volumes:
        - wordpress:/var/www/html


  mysql:
    image: "mysql:5.7"
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: somewordpress
        MYSQL_DATABASE: wordpress
        MYSQL_USER: exampleuser
        MYSQL_PASSWORD: examplepass  
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db: