version: '3.3'

services:
  db:
    image: 'mysql:5.7'
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: somewordpress
        MYSQL_DATABASE: wordpress
        MYSQL_USER: exampleuser
        MYSQL_PASSWORD: examplepass  
    volumes:
      - db:/var/lib/mysql


  wordpress:
    depends_on:
     - db
    image: wp-image
    restart: always
    ports:
        - "5000:80"
    environment:
        WORDPRESS_DB_HOST: db:3306
        WORDPRESS_DB_USER: exampleuser
        WORDPRESS_DB_PASSWORD: examplepass
    volumes:
        - wp-content:/var/www/html/wp-content

volumes:
  wp-content:
  db: